### ISSUE TITLE
Feature Request: adapter for Home Assistant

### ISSUE THREAD

**Issue by MartinKuhl** [oelison/ioBroker.mediola-gateway#28]
Hi @oelison,

I really appreciate your effort for the mediola gateway. 
Would you be able to also write an adapter for the Home Assistant plattform to support the mediola gateway also there?

**Comment by oelison** [comment]
Hi @MartinKuhl,
Sorry, but I have no spare time for that. I do not use this platform. This will result in very bad result.
Maybe you could make an adapter request on that platform and link my code there. Support for interpretation is also possible.
