### ISSUE TITLE
Feature requests: Elero roller shutter

### ISSUE THREAD

**Issue by CsL-007** [oelison/ioBroker.mediola-gateway#35]
Hi!

Like your work, maybe can you add Elero blind support too?
Here is what Elero calls looks like: 
{"type":"ER","sid":"10","adr":"03","state":"1002","ts":{"m":"6516B9E4"}}

Thanks in advance!

**Comment by oelison** [comment]
Hi @CsL-007 
are you able to record the calls to the mediola gateway for up, down and stop? And if it is possible some percentage of opening or closing?
They might look like:
`/cmd?XC_FNC=SendSC&type=ER&data=`
What type of mediola gateway you have?

**Comment by CsL-007** [comment]
My gateway is V6plus. Able to move blind up,down, stop with html command. Elero blinds have no percentage, just open or close status, but it never worked me. When use /cmd?XC_FNC=SendSC&type=ER&data=0101 get this response: {"XC_SUC": {}}.

**Comment by oelison** [comment]
Could you give me the calls for up, down and stop? And could you execute `http://ipaddress/command?XC_FNC=getstates` and give me the result after each action?
And could you switch the mediola adapter into debug during this time and give me all messages?

**Comment by CsL-007** [comment]
Here is what I'm able to get:

GET:/cmd?XC_FNC=SendSC&type=ER&data=0101&auth=************ -> HTTP:304
HTTP:304
GET:/cmd?XC_FNC=SendSC&type=ER&data=0100&auth=************ -> HTTP:304
GET:/ -> HTTP:304
GET:/cmd?XC_FNC=SendSC&type=ER&data=0102&auth=************ -> HTTP:304
GET:/ -> HTTP:304

Down: {"type":"ER","sid":"0E","adr":"01","state":"100B","ts":{"m":"65191B4C"}}
Up: {"type":"ER","sid":"0E","adr":"01","state":"1001","ts":{"m":"65191A15"}}
Middle: {"type":"ER","sid":"0E","adr":"01","state":"100D","ts":{"m":"65191B2E"}}

GET:/cmd?XC_FNC=getStates&at=47ca3b7de2be372bdee71fe63cabd65e -> HTTP:200
GET:/cmd?XC_FNC=SendSC&type=ER&data=0100&at=47ca3b7de2be372bdee71fe63cabd65e -> HTTP:200
GET:/cmd?XC_FNC=getStates&at=47ca3b7de2be372bdee71fe63cabd65e -> HTTP:200
GET:/cmd?XC_FNC=SendSC&type=ER&data=0102&at=47ca3b7de2be372bdee71fe63cabd65e -> HTTP:200
GET:/cmd?XC_FNC=getStates&at=47ca3b7de2be372bdee71fe63cabd65e -> HTTP:200
GET:/cmd?XC_FNC=SendSC&type=ER&data=0100&at=47ca3b7de2be372bdee71fe63cabd65e -> HTTP:304
GET:/cmd?XC_FNC=getStates&at=47ca3b7de2be372bdee71fe63cabd65e -> HTTP:200
GET:/cmd?XC_FNC=SendSC&type=ER&data=0101&at=47ca3b7de2be372bdee71fe63cabd65e -> HTTP:200
GET:/cmd?XC_FNC=getStates&at=47ca3b7de2be372bdee71fe63cabd65e -> HTTP:200

**Comment by oelison** [comment]
@CsL-007 Could you try out the https://github.com/oelison/ioBroker.mediola-gateway/tree/elero_roller_shutter
Simply activate the expert mode. Go to adapter. Click the cat from github. And in userdefined use the given link.
If there are problems, you could answer here or for faster communication send a personal mail to the mail address in the readme.

**Comment by CsL-007** [comment]
No blind find, get this error: mediola device rejected the request: [object Object]
Maybe auth not work?

**Comment by oelison** [comment]
Could you execute `http://ipaddress/command?XC_FNC=getstates` in a webbrowser and give me the result?
Maybe you need to add a user `abcd` with pass `efgh` and try this: `http://ipaddress/command?XC_USER=abcd&CX_PASS=efgh&XC_FNC=getstates`
`abcd` and `efgh` you could replace as you need.
The result must be something with success.

**Comment by CsL-007** [comment]
**command?XC_FNC=getstates&auth=mypassword** work only, Mediola api document write this parameter not the user and password combo

**Comment by oelison** [comment]
I will add this as an option, too.

**Comment by oelison** [comment]
https://github.com/oelison/ioBroker.mediola-gateway/tree/authParam
Here I have added the auth key. Make sure, that the password and at least the name is empty.

**Comment by oelison** [comment]
No further request open, maybe solved.
