### ISSUE TITLE
Question WIR shutter State query

### ISSUE THREAD

**Issue by tester277** [oelison/ioBroker.mediola-gateway#44]
Hi,
Thank You for Itegration of WIR shutter to iobroker.
From your experience, the state of a WIR roller blind for position can also be queried via http query (on the gateway or iobroker)? The status of all devices can be checked.
However, I only need the one return value.
Thank You

**Comment by oelison** [comment]
Hi, I do not get your question. I have no WIR shutter, so I can not test it or see what you are seeing. Could you give me an example? The result that you have and the result you are expecting?

**Comment by oelison** [comment]
Reopen with new information.
